matchBlocks=dirt coarse_dirt grass_block dirt_path podzol stone granite diorite andesite sandstone smooth_sandstone oak_planks spruce_planks birch_planks jungle_planks acacia_planks terracotta white_terracotta light_gray_terracotta gray_terracotta black_terracotta brown_terracotta red_terracotta orange_terracotta yellow_terracotta lime_terracotta green_terracotta cyan_terracotta light_blue_terracotta blue_terracotta purple_terracotta magenta_terracotta pink_terracotta dirt_path deepslate infested_deepslate deepslate_coal_ore deepslate_iron_ore deepslate_copper_ore deepslate_gold_ore deepslate_redstone_ore deepslate_emerald_ore deepslate_lapis_ore deepslate_diamond_ore
method=overlay
tiles=0-16
connect=block
weight=10
layer=cutout_mipped
connectBlocks=cobblestone cobblestone_slab:type=double infested_cobblestone