matchBlocks=dirt coarse_dirt grass_block dirt_path podzol stone cobblestone cobblestone_slab:type=double infested_cobblestone granite diorite andesite sandstone smooth_sandstone oak_planks spruce_planks birch_planks jungle_planks acacia_planks dark_oak_planks white_terracotta dirt_path deepslate infested_deepslate deepslate_coal_ore deepslate_iron_ore deepslate_copper_ore deepslate_gold_ore deepslate_redstone_ore deepslate_emerald_ore deepslate_lapis_ore deepslate_diamond_ore
method=overlay
tiles=0-16
connect=block
layer=cutout_mipped
connectBlocks=mossy_cobblestone mossy_cobblestone_slab:type=double