matchBlocks=netherrack nether_quartz_ore terracotta stone diorite andesite stone_slab:type=double sandstone_slab:type=double gold_ore iron_ore coal_ore lapis_ore diamond_ore redstone_ore emerald_ore copper_ore tuff deepslate infested_deepslate deepslate_coal_ore deepslate_iron_ore deepslate_copper_ore deepslate_gold_ore deepslate_redstone_ore deepslate_emerald_ore deepslate_lapis_ore deepslate_diamond_ore
method=overlay
tiles=0-16
connect=block
weight=2
layer=translucent
connectBlocks=granite