matchBlocks=stone deepslate light_blue_terracotta blue_terracotta purple_terracotta magenta_terracotta pink_terracotta
method=overlay
tiles=0-16
connect=block
weight=2
layer=translucent
connectBlocks=cyan_terracotta