matchBlocks=stone andesite coal_ore lapis_ore iron_ore redstone_ore gold_ore diamond_ore emerald_ore copper_ore tuff deepslate infested_deepslate deepslate_coal_ore deepslate_iron_ore deepslate_copper_ore deepslate_gold_ore deepslate_redstone_ore deepslate_emerald_ore deepslate_lapis_ore deepslate_diamond_ore
method=overlay
tiles=0-16
connect=block
weight=2
layer=translucent
connectBlocks=diorite