matchBlocks=stone deepslate lime_terracotta green_terracotta cyan_terracotta light_blue_terracotta blue_terracotta purple_terracotta magenta_terracotta pink_terracotta
method=overlay
tiles=0-16
connect=block
weight=2
layer=translucent
connectBlocks=yellow_terracotta