matchBlocks=stone granite diorite andesite dirt coarse_dirt podzol gold_ore iron_ore coal_ore lapis_ore sandstone diamond_ore redstone_ore netherrack soul_sand soul_soil mycelium end_stone nether_quartz_ore red_sandstone dirt_path clay tuff deepslate infested_deepslate deepslate_coal_ore deepslate_iron_ore deepslate_copper_ore deepslate_gold_ore deepslate_redstone_ore deepslate_emerald_ore deepslate_lapis_ore deepslate_diamond_ore grass_block gravel
method=overlay
tiles=0-16
connect=block
weight=2
layer=translucent
connectBlocks=suspicious_gravel